# Getting Started with Julia in Colab/Jupyter
You can either run this notebook in Google Colab, or using Jupyter on your own machine.

## Running on Google Colab
1. Work on a copy of this notebook: _File_ > _Save a copy in Drive_ (you will need a Google account). Alternatively, you can download the notebook using _File_ > _Download .ipynb_, then upload it to [Colab](https://colab.research.google.com/).
2. Execute the following cell (click on it and press Ctrl+Enter) to install Julia, IJulia (the Jupyter kernel for Julia) and other packages. You can update `JULIA_VERSION` and the other parameters, if you know what you're doing. Installation takes 2-3 minutes.
3. Reload this page (press Ctrl+R, or ⌘+R, or the F5 key) and continue to the _Checking the Installation_ section.

* _Note_: If your Colab Runtime gets reset (e.g., due to inactivity), repeat steps 2 and 3.

In [ ]:
%%shell
set -e

#---------------------------------------------------#
JULIA_VERSION="1.6.0" # any version ≥ 0.7.0
JULIA_PACKAGES="IJulia"
JULIA_PACKAGES_IF_GPU="CUDA"
JULIA_NUM_THREADS=4
#---------------------------------------------------#

if [ -n "$COLAB_GPU" ] && [ -z `which julia` ]; then
  # Install Julia
  JULIA_VER=`cut -d '.' -f -2 <<< "$JULIA_VERSION"`
  echo "Installing Julia $JULIA_VERSION on the current Colab Runtime..."
  BASE_URL="https://julialang-s3.julialang.org/bin/linux/x64"
  URL="$BASE_URL/$JULIA_VER/julia-$JULIA_VERSION-linux-x86_64.tar.gz"
  wget -nv $URL -O /tmp/julia.tar.gz # -nv means "not verbose"
  tar -x -f /tmp/julia.tar.gz -C /usr/local --strip-components 1
  rm /tmp/julia.tar.gz

  # Install Packages
  if [ "$COLAB_GPU" = "1" ]; then
      JULIA_PACKAGES="$JULIA_PACKAGES $JULIA_PACKAGES_IF_GPU"
  fi
  for PKG in `echo $JULIA_PACKAGES`; do
    echo "Installing Julia package $PKG..."
    julia -e 'using Pkg; pkg"add '$PKG'; precompile;"' &> /dev/null
  done

  # Install kernel and rename it to "julia"
  echo "Installing IJulia kernel..."
  julia -e 'using IJulia; IJulia.installkernel("julia", env=Dict(
      "JULIA_NUM_THREADS"=>"'"$JULIA_NUM_THREADS"'"))'
  KERNEL_DIR=`julia -e "using IJulia; print(IJulia.kerneldir())"`
  KERNEL_NAME=`ls -d "$KERNEL_DIR"/julia*`
  mv -f $KERNEL_NAME "$KERNEL_DIR"/julia  

  echo ''
  echo "Successfully installed `julia -v`!"
  echo "Please reload this page (press Ctrl+R, ⌘+R, or the F5 key) then"
  echo "jump to the 'Checking the Installation' section."
fi

Installing Julia 1.6.0 on the current Colab Runtime...
2021-11-25 11:35:28 URL:https://storage.googleapis.com/julialang2/bin/linux/x64/1.6/julia-1.6.0-linux-x86_64.tar.gz [112838927/112838927] -> "/tmp/julia.tar.gz" [1]
Installing Julia package IJulia...
Installing IJulia kernel...
[ Info: Installing julia kernelspec in /root/.local/share/jupyter/kernels/julia-1.6

Please reload this page (press Ctrl+R, ⌘+R, or the F5 key) then
jump to the 'Checking the Installation' section.


## Checking the Installation
The `versioninfo()` function should print your Julia version and some other info about the system (if you ever ask for help or file an issue about Julia, you should always provide this information).

In [1]:
versioninfo()

Julia Version 1.6.0
Commit f9720dc2eb (2021-03-24 12:55 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU @ 2.20GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, broadwell)
Environment:
  JULIA_NUM_THREADS = 4


In [23]:
using Statistics
using LinearAlgebra

# Create a null vector of size 10

In [2]:
Z = zeros(Int8,10)
Z

10-element Vector{Int8}:
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0

# How to find the memory size of any array

In [3]:
Z = zeros(Int8,10,10)
Z

10×10 Matrix{Int8}:
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0

In [4]:
size_bytes(x) = Base.format_bytes(Base.summarysize(x))
size_bytes(Z)

"140 bytes"

# How to get the documentation of the numpy add function from the command line?

In [5]:
? +

search: +



```
+(x, y...)
```

Addition operator. `x+y+z+...` calls this function with all arguments, i.e. `+(x, y, z, ...)`.

# Examples

```jldoctest
julia> 1 + 20 + 4
25

julia> +(1, 20, 4)
25
```

---

```
dt::Date + t::Time -> DateTime
```

The addition of a `Date` with a `Time` produces a `DateTime`. The hour, minute, second, and millisecond parts of the `Time` are used along with the year, month, and day of the `Date` to create the new `DateTime`. Non-zero microseconds or nanoseconds in the `Time` type will result in an `InexactError` being thrown.


In [6]:
? zero

search: zero zeros iszero set_zero_subnormals get_zero_subnormals count_zeros



```
zero(x)
zero(::Type)
```

Get the additive identity element for the type of `x` (`x` can also specify the type itself).

# Examples

```jldoctest
julia> zero(1)
0

julia> zero(big"2.0")
0.0

julia> zero(rand(2,2))
2×2 Matrix{Float64}:
 0.0  0.0
 0.0  0.0
```


# Create a null vector of size 10 but the fifth value which is 1

In [7]:
Z = zeros(Int8,10)
Z[5] = 1
Z

10-element Vector{Int8}:
 0
 0
 0
 0
 1
 0
 0
 0
 0
 0

# Create a vector with values ranging from 10 to 49

In [8]:
Z = [10:50]

1-element Vector{UnitRange{Int64}}:
 10:50

In [9]:
# If you actually want it as an array for some reason 
Z = [10:50;]
Z

41-element Vector{Int64}:
 10
 11
 12
 13
 14
 15
 16
 17
 18
 19
 20
 21
 22
  ⋮
 39
 40
 41
 42
 43
 44
 45
 46
 47
 48
 49
 50

# Reverse a vector (first element becomes last)

In [10]:
Z = zeros(Int8,10)
Z[1] = 1
print(Z)
reverse!(Z)
Z

Int8[1, 0, 0, 0, 0, 0, 0, 0, 0, 0]

10-element Vector{Int8}:
 0
 0
 0
 0
 0
 0
 0
 0
 0
 1

# Create a 3x3 matrix with values ranging from 0 to 8


In [11]:
Z = [0:8;]
Z = reshape(Z,(3,3))

3×3 Matrix{Int64}:
 0  3  6
 1  4  7
 2  5  8

In [12]:
# This is likely a more efficient method
Z = reshape(Vector(0:8),(3,3))

3×3 Matrix{Int64}:
 0  3  6
 1  4  7
 2  5  8

# Find indices of non-zero elements from [1,2,0,0,4,0]

In [13]:
Z = [1,2,0,0,4,0]
print(findall(iszero,Z))
Z[findall(iszero,Z)]

[3, 4, 6]

3-element Vector{Int64}:
 0
 0
 0


# Create a 3x3 identity matrix

In [15]:
1.0I

# This is a really profound answer to the question involving a deep dive into Julia's philosophy and computing in general 
# https://stackoverflow.com/a/57270841/14274188 you should probably read this answer before using this particular code.

UniformScaling{Float64}
1.0*I

In [16]:
Z = Matrix{Int8}(I,3,3)

3×3 Matrix{Int8}:
 1  0  0
 0  1  0
 0  0  1

# Create a 3x3x3 array with random values

In [17]:
Z = rand(Int,(3,3,3))
Z

3×3×3 Array{Int64, 3}:
[:, :, 1] =
  4649380487668320894  -2067609935911406775  -9052330451448747045
  8628971687186939769   -867815689261577562   1840202765238402212
 -4884528182175607249  -4404521423747731278  -8998852740546798404

[:, :, 2] =
  8590037858733402229  1321212195272907057  -2478173318768669627
   593013185004534170  -245860346644374951  -1987782186870759815
 -3650865187632392047  3736581548044767584    -82465049361832386

[:, :, 3] =
  7060433879426830401   6360487648502011630  -1202246491082184836
 -2589852269349299233  -8760731057040967125   4038173716668623663
 -8348191426236813985   3542268372806661333   7248309638494795629

# Create a 10x10 array with random values and find the minimum and maximum values

In [18]:
Z = rand(Int,(10,10))

10×10 Matrix{Int64}:
  6698386989330676646  -5910630967838983425  …   3051058284729132481
  3515562006200034419   4900246215548472729      5647151162714783914
  4298296650232372604  -9015867304391303047     -7174884628780340071
  2507721041720753525   5481647304366426025      7522880679136050118
 -7444607153175415232   1390221328696253109     -3749349230553727548
  2214116093327203255   1144548660292033624  …  -7512426415199545077
 -8029317399591488123  -6964477807991941775     -3624178711240662728
 -9160061762521676002     85645186292344738      3778561982328676231
 -6405483611013440016  -5884717771638824377      2440070257791391101
 -7958762338775552828   7885801063505875059       573685350737470165

In [19]:
minimum(Z)

-9160061762521676002

In [20]:
maximum(Z)

9149309764848341522

# Create a random vector of size 30 and find the mean value

In [24]:
Z = Vector(rand(Int,10))

# Kinda basic method
sum(Z)/length(Z)

3.608860241905671e17

In [25]:
# This is not a part of the standard library and is instead imported from Statistics, yes not one of the best decisions Julia ever made
mean(Z)

3.608860241905672e17

# Create a 2d array with 1 on the border and 0 inside

In [35]:
Z = ones(10, 10)
Z[2:end-1, 2:end-1] .= 0
Z
# Okay there are a few bits here that we have to address:
# Right of the bat Julia uses 1-based indexing as you probably already know
# The end keyword represents the end of a dimension in Julia, It provides a more explicit way to specify indexes.
# Finally the . operator is used for broadcasting. Julia does not automatically write 0 everywhere if you use just the assignment operator. This can often trip people and instead the . operator provides an explicit broadcasting method

10×10 Matrix{Float64}:
 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0
 1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0
 1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0
 1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0
 1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0
 1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0
 1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0
 1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0
 1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0
 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0

# How to add a border (filled with 0's) around an existing array?

In [41]:
len_mat = 9
Z = ones(Int8, len_mat, len_mat)
borderZ = zeros(Int8, len_mat + 2, len_mat + 2)
borderZ[2:end-1, 2:end-1] = Z
borderZ
# Ok so this is very much an extremely hacky way to do this but I could find a good way to go about this.
# If you are using this in a context of images processing then Image Filtering has a way described here https://discourse.julialang.org/t/is-there-any-padding-function-available-to-pad-a-matrix-or-array/8521/3
# PaddedViews.jl might be an option too if you are using this a lot

11×11 Matrix{Int8}:
 0  0  0  0  0  0  0  0  0  0  0
 0  1  1  1  1  1  1  1  1  1  0
 0  1  1  1  1  1  1  1  1  1  0
 0  1  1  1  1  1  1  1  1  1  0
 0  1  1  1  1  1  1  1  1  1  0
 0  1  1  1  1  1  1  1  1  1  0
 0  1  1  1  1  1  1  1  1  1  0
 0  1  1  1  1  1  1  1  1  1  0
 0  1  1  1  1  1  1  1  1  1  0
 0  1  1  1  1  1  1  1  1  1  0
 0  0  0  0  0  0  0  0  0  0  0

In [39]:
Z = ones(Int8,9,9)

9×9 Matrix{Int8}:
 1  1  1  1  1  1  1  1  1
 1  1  1  1  1  1  1  1  1
 1  1  1  1  1  1  1  1  1
 1  1  1  1  1  1  1  1  1
 1  1  1  1  1  1  1  1  1
 1  1  1  1  1  1  1  1  1
 1  1  1  1  1  1  1  1  1
 1  1  1  1  1  1  1  1  1
 1  1  1  1  1  1  1  1  1