# Getting Started with Julia in Colab/Jupyter
You can either run this notebook in Google Colab, or using Jupyter on your own machine.

## Running on Google Colab
1. Work on a copy of this notebook: _File_ > _Save a copy in Drive_ (you will need a Google account). Alternatively, you can download the notebook using _File_ > _Download .ipynb_, then upload it to [Colab](https://colab.research.google.com/).
2. Execute the following cell (click on it and press Ctrl+Enter) to install Julia, IJulia (the Jupyter kernel for Julia) and other packages. You can update `JULIA_VERSION` and the other parameters, if you know what you're doing. Installation takes 2-3 minutes.
3. Reload this page (press Ctrl+R, or ⌘+R, or the F5 key) and continue to the _Checking the Installation_ section.

* _Note_: If your Colab Runtime gets reset (e.g., due to inactivity), repeat steps 2 and 3.

In [ ]:
%%shell
set -e

#---------------------------------------------------#
JULIA_VERSION="1.6.0" # any version ≥ 0.7.0
JULIA_PACKAGES="IJulia"
JULIA_PACKAGES_IF_GPU="CUDA"
JULIA_NUM_THREADS=4
#---------------------------------------------------#

if [ -n "$COLAB_GPU" ] && [ -z `which julia` ]; then
  # Install Julia
  JULIA_VER=`cut -d '.' -f -2 <<< "$JULIA_VERSION"`
  echo "Installing Julia $JULIA_VERSION on the current Colab Runtime..."
  BASE_URL="https://julialang-s3.julialang.org/bin/linux/x64"
  URL="$BASE_URL/$JULIA_VER/julia-$JULIA_VERSION-linux-x86_64.tar.gz"
  wget -nv $URL -O /tmp/julia.tar.gz # -nv means "not verbose"
  tar -x -f /tmp/julia.tar.gz -C /usr/local --strip-components 1
  rm /tmp/julia.tar.gz

  # Install Packages
  if [ "$COLAB_GPU" = "1" ]; then
      JULIA_PACKAGES="$JULIA_PACKAGES $JULIA_PACKAGES_IF_GPU"
  fi
  for PKG in `echo $JULIA_PACKAGES`; do
    echo "Installing Julia package $PKG..."
    julia -e 'using Pkg; pkg"add '$PKG'; precompile;"' &> /dev/null
  done

  # Install kernel and rename it to "julia"
  echo "Installing IJulia kernel..."
  julia -e 'using IJulia; IJulia.installkernel("julia", env=Dict(
      "JULIA_NUM_THREADS"=>"'"$JULIA_NUM_THREADS"'"))'
  KERNEL_DIR=`julia -e "using IJulia; print(IJulia.kerneldir())"`
  KERNEL_NAME=`ls -d "$KERNEL_DIR"/julia*`
  mv -f $KERNEL_NAME "$KERNEL_DIR"/julia  

  echo ''
  echo "Successfully installed `julia -v`!"
  echo "Please reload this page (press Ctrl+R, ⌘+R, or the F5 key) then"
  echo "jump to the 'Checking the Installation' section."
fi

Installing Julia 1.6.0 on the current Colab Runtime...
2021-11-29 11:50:07 URL:https://storage.googleapis.com/julialang2/bin/linux/x64/1.6/julia-1.6.0-linux-x86_64.tar.gz [112838927/112838927] -> "/tmp/julia.tar.gz" [1]
Installing Julia package IJulia...


## Checking the Installation
The `versioninfo()` function should print your Julia version and some other info about the system (if you ever ask for help or file an issue about Julia, you should always provide this information).

In [1]:
versioninfo()

Julia Version 1.6.0
Commit f9720dc2eb (2021-03-24 12:55 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU @ 2.20GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, broadwell)
Environment:
  JULIA_NUM_THREADS = 4


In [2]:
using Statistics
using LinearAlgebra

# Create a null vector of size 10

In [3]:
Z = zeros(Int8,10)
Z

10-element Vector{Int8}:
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0

# How to find the memory size of any array

In [4]:
Z = zeros(Int8,10,10)
Z

10×10 Matrix{Int8}:
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0

In [5]:
size_bytes(x) = Base.format_bytes(Base.summarysize(x))
size_bytes(Z)

"140 bytes"

# How to get the documentation of the numpy add function from the command line?

In [6]:
? +

search: +



```
+(x, y...)
```

Addition operator. `x+y+z+...` calls this function with all arguments, i.e. `+(x, y, z, ...)`.

# Examples

```jldoctest
julia> 1 + 20 + 4
25

julia> +(1, 20, 4)
25
```

---

```
dt::Date + t::Time -> DateTime
```

The addition of a `Date` with a `Time` produces a `DateTime`. The hour, minute, second, and millisecond parts of the `Time` are used along with the year, month, and day of the `Date` to create the new `DateTime`. Non-zero microseconds or nanoseconds in the `Time` type will result in an `InexactError` being thrown.


In [7]:
? zero

search: zero zeros ZeroPivotException iszero set_zero_subnormals



```
zero(x)
zero(::Type)
```

Get the additive identity element for the type of `x` (`x` can also specify the type itself).

# Examples

```jldoctest
julia> zero(1)
0

julia> zero(big"2.0")
0.0

julia> zero(rand(2,2))
2×2 Matrix{Float64}:
 0.0  0.0
 0.0  0.0
```


# Create a null vector of size 10 but the fifth value which is 1

In [8]:
Z = zeros(Int8,10)
Z[5] = 1
Z

10-element Vector{Int8}:
 0
 0
 0
 0
 1
 0
 0
 0
 0
 0

# Create a vector with values ranging from 10 to 49

In [9]:
Z = [10:50]

1-element Vector{UnitRange{Int64}}:
 10:50

In [10]:
# If you actually want it as an array for some reason 
Z = [10:50;]
Z

41-element Vector{Int64}:
 10
 11
 12
 13
 14
 15
 16
 17
 18
 19
 20
 21
 22
  ⋮
 39
 40
 41
 42
 43
 44
 45
 46
 47
 48
 49
 50

# Reverse a vector (first element becomes last)

In [11]:
Z = zeros(Int8,10)
Z[1] = 1
print(Z)
reverse!(Z)
Z

Int8[1, 0, 0, 0, 0, 0, 0, 0, 0, 0]

10-element Vector{Int8}:
 0
 0
 0
 0
 0
 0
 0
 0
 0
 1

# Create a 3x3 matrix with values ranging from 0 to 8


In [12]:
Z = [0:8;]
Z = reshape(Z,(3,3))

3×3 Matrix{Int64}:
 0  3  6
 1  4  7
 2  5  8

In [13]:
# This is likely a more efficient method
Z = reshape(Vector(0:8),(3,3))

3×3 Matrix{Int64}:
 0  3  6
 1  4  7
 2  5  8

# Find indices of non-zero elements from [1,2,0,0,4,0]

In [14]:
Z = [1,2,0,0,4,0]
print(findall(iszero,Z))
Z[findall(iszero,Z)]

[3, 4, 6]

3-element Vector{Int64}:
 0
 0
 0


# Create a 3x3 identity matrix

In [15]:
1.0I

# This is a really profound answer to the question involving a deep dive into Julia's philosophy and computing in general 
# https://stackoverflow.com/a/57270841/14274188 you should probably read this answer before using this particular code.

UniformScaling{Float64}
1.0*I

In [16]:
Z = Matrix{Int8}(I,3,3)

3×3 Matrix{Int8}:
 1  0  0
 0  1  0
 0  0  1

# Create a 3x3x3 array with random values

In [17]:
Z = rand(Int,(3,3,3))
Z

3×3×3 Array{Int64, 3}:
[:, :, 1] =
 -8256703737528188950   1394692683640299653  -1189500521292870627
  7617712784565729170  -2245526996519471630   2034540011288260978
  7219763992562110900  -1101003317557733122   2082529645388415730

[:, :, 2] =
  3456068601264514747  2440469809693543504   3148999289058691899
 -6647107438700649538  4287912972608105062  -5971115822647636929
    49461717585334702  6023849243641078602   4324241011587377169

[:, :, 3] =
  7048270689293475682  -9005068027181725867   9132830545355469994
 -6934732739891674508   8950722776083279824   -460229056516456923
  2621127760443490381   4338291894234633671  -6631956438026973628

# Create a 10x10 array with random values and find the minimum and maximum values

In [18]:
Z = rand(Int,(10,10))

10×10 Matrix{Int64}:
  3426058487764615921  -7035133869488045731  …  -2369536187607755231
 -6802436546650682443    954277926499280434     -1250909151763192457
  3867782567260032369  -8399008502013792087      6133022319373047235
  7998685179370904134   5218101146423205012       586439792002949281
 -9165916128682622693  -2881567001900688868      8894015419992135618
 -1261582839315080947   8349300995804241461  …   4491626385988202838
 -6931519337177881120  -2608225662300391475     -3512379889895926061
  2195806743954096081  -4755433013121841986      7682655932705135579
  3242977712179839618  -7123779267057535198       639611427072246915
 -6666238143181501671   9062354053597734272      3556129174089640428

In [19]:
minimum(Z)

-9194799497573751938

In [20]:
maximum(Z)

9207812304578395777

# Create a random vector of size 30 and find the mean value

In [21]:
Z = Vector(rand(Int,10))

# Kinda basic method
sum(Z)/length(Z)

2.3489890101955012e16

In [22]:
# This is not a part of the standard library and is instead imported from Statistics, yes not one of the best decisions Julia ever made
mean(Z)

1.86816429747291e18

# Create a 2d array with 1 on the border and 0 inside

In [23]:
Z = ones(10, 10)
Z[2:end-1, 2:end-1] .= 0
Z
# Okay there are a few bits here that we have to address:
# Right of the bat Julia uses 1-based indexing as you probably already know
# The end keyword represents the end of a dimension in Julia, It provides a more explicit way to specify indexes.
# Finally the . operator is used for broadcasting. Julia does not automatically write 0 everywhere if you use just the assignment operator. This can often trip people and instead the . operator provides an explicit broadcasting method

10×10 Matrix{Float64}:
 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0
 1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0
 1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0
 1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0
 1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0
 1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0
 1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0
 1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0
 1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0
 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0

# How to add a border (filled with 0's) around an existing array?

In [24]:
len_mat = 9
Z = ones(Int8, len_mat, len_mat)
borderZ = zeros(Int8, len_mat + 2, len_mat + 2)
borderZ[2:end-1, 2:end-1] = Z
borderZ
# Ok so this is very much an extremely hacky way to do this but I could find a good way to go about this.
# If you are using this in a context of images processing then Image Filtering has a way described here https://discourse.julialang.org/t/is-there-any-padding-function-available-to-pad-a-matrix-or-array/8521/3
# PaddedViews.jl might be an option too if you are using this a lot

11×11 Matrix{Int8}:
 0  0  0  0  0  0  0  0  0  0  0
 0  1  1  1  1  1  1  1  1  1  0
 0  1  1  1  1  1  1  1  1  1  0
 0  1  1  1  1  1  1  1  1  1  0
 0  1  1  1  1  1  1  1  1  1  0
 0  1  1  1  1  1  1  1  1  1  0
 0  1  1  1  1  1  1  1  1  1  0
 0  1  1  1  1  1  1  1  1  1  0
 0  1  1  1  1  1  1  1  1  1  0
 0  1  1  1  1  1  1  1  1  1  0
 0  0  0  0  0  0  0  0  0  0  0

In [25]:
Z = ones(Int8,9,9)

9×9 Matrix{Int8}:
 1  1  1  1  1  1  1  1  1
 1  1  1  1  1  1  1  1  1
 1  1  1  1  1  1  1  1  1
 1  1  1  1  1  1  1  1  1
 1  1  1  1  1  1  1  1  1
 1  1  1  1  1  1  1  1  1
 1  1  1  1  1  1  1  1  1
 1  1  1  1  1  1  1  1  1
 1  1  1  1  1  1  1  1  1

# Create a 5x5 matrix with values 1,2,3,4 just below the diagonal 

In [26]:
diagonal = [1, 2, 3, 4]
ld = Bidiagonal(zeros(5), diagonal, :L)
# : in this context is an identifier essentially used to identify an entity. Here if you use :U instead, that uses a different implementation which would place the diagonal vector on top of zeros instead

5×5 Bidiagonal{Float64, Vector{Float64}}:
 0.0   ⋅    ⋅    ⋅    ⋅ 
 1.0  0.0   ⋅    ⋅    ⋅ 
  ⋅   2.0  0.0   ⋅    ⋅ 
  ⋅    ⋅   3.0  0.0   ⋅ 
  ⋅    ⋅    ⋅   4.0  0.0

# Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [27]:
arr = rand(Int8, (6, 7, 8))
c_x = CartesianIndices(arr)
arr[c_x[100]]

-89

# Create a checkerboard 8x8 matrix using the tile function

In [28]:
base_mat = [[1, 0] [0, 1]]
repeat(base_mat,4,4)

8×8 Matrix{Int64}:
 1  0  1  0  1  0  1  0
 0  1  0  1  0  1  0  1
 1  0  1  0  1  0  1  0
 0  1  0  1  0  1  0  1
 1  0  1  0  1  0  1  0
 0  1  0  1  0  1  0  1
 1  0  1  0  1  0  1  0
 0  1  0  1  0  1  0  1

# Normalize a 5x5 random matrix

In [33]:
Z = 2rand(5,5)

5×5 Matrix{Float64}:
 1.70084   0.928701   0.583323  0.954439  0.192044
 1.21564   0.749247   1.86456   1.90508   1.94866
 1.54496   0.0350824  0.585315  0.196124  1.70807
 0.774875  0.621097   1.8204    1.6112    1.63568
 1.96227   0.452761   0.417139  1.14688   0.972317

In [34]:
normalize!(Z)

5×5 Matrix{Float64}:
 0.269825  0.147331    0.0925394  0.151414   0.0304662
 0.192851  0.118862    0.295797   0.302226   0.309139
 0.245095  0.00556554  0.0928553  0.0311134  0.270972
 0.122927  0.098532    0.288791   0.255604   0.259487
 0.311298  0.0718268   0.0661756  0.181943   0.15425

# Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

In [37]:
Z₁ = ones(5,3)
Z₂ = ones(3,2)
Z₁*Z₂
# Yeah bit of a show off but that's just objectively cool

5×2 Matrix{Float64}:
 3.0  3.0
 3.0  3.0
 3.0  3.0
 3.0  3.0
 3.0  3.0

# Given a 1D array, negate all elements which are between 3 and 8, in place.

In [58]:
Z = [1:11;]
replace!(x -> (3 .<= x .<= 8) ? -x : x,Z)

11-element Vector{Int64}:
  1
  2
 -3
 -4
 -5
 -6
 -7
 -8
  9
 10
 11