# Getting Started with Julia in Colab/Jupyter
You can either run this notebook in Google Colab, or using Jupyter on your own machine.

## Running on Google Colab
1. Work on a copy of this notebook: _File_ > _Save a copy in Drive_ (you will need a Google account). Alternatively, you can download the notebook using _File_ > _Download .ipynb_, then upload it to [Colab](https://colab.research.google.com/).
2. Execute the following cell (click on it and press Ctrl+Enter) to install Julia, IJulia (the Jupyter kernel for Julia) and other packages. You can update `JULIA_VERSION` and the other parameters, if you know what you're doing. Installation takes 2-3 minutes.
3. Reload this page (press Ctrl+R, or ⌘+R, or the F5 key) and continue to the _Checking the Installation_ section.

* _Note_: If your Colab Runtime gets reset (e.g., due to inactivity), repeat steps 2 and 3.

In [ ]:
%%shell
set -e

#---------------------------------------------------#
JULIA_VERSION="1.6.0" # any version ≥ 0.7.0
JULIA_PACKAGES="IJulia"
JULIA_PACKAGES_IF_GPU="CUDA"
JULIA_NUM_THREADS=4
#---------------------------------------------------#

if [ -n "$COLAB_GPU" ] && [ -z `which julia` ]; then
  # Install Julia
  JULIA_VER=`cut -d '.' -f -2 <<< "$JULIA_VERSION"`
  echo "Installing Julia $JULIA_VERSION on the current Colab Runtime..."
  BASE_URL="https://julialang-s3.julialang.org/bin/linux/x64"
  URL="$BASE_URL/$JULIA_VER/julia-$JULIA_VERSION-linux-x86_64.tar.gz"
  wget -nv $URL -O /tmp/julia.tar.gz # -nv means "not verbose"
  tar -x -f /tmp/julia.tar.gz -C /usr/local --strip-components 1
  rm /tmp/julia.tar.gz

  # Install Packages
  if [ "$COLAB_GPU" = "1" ]; then
      JULIA_PACKAGES="$JULIA_PACKAGES $JULIA_PACKAGES_IF_GPU"
  fi
  for PKG in `echo $JULIA_PACKAGES`; do
    echo "Installing Julia package $PKG..."
    julia -e 'using Pkg; pkg"add '$PKG'; precompile;"' &> /dev/null
  done

  # Install kernel and rename it to "julia"
  echo "Installing IJulia kernel..."
  julia -e 'using IJulia; IJulia.installkernel("julia", env=Dict(
      "JULIA_NUM_THREADS"=>"'"$JULIA_NUM_THREADS"'"))'
  KERNEL_DIR=`julia -e "using IJulia; print(IJulia.kerneldir())"`
  KERNEL_NAME=`ls -d "$KERNEL_DIR"/julia*`
  mv -f $KERNEL_NAME "$KERNEL_DIR"/julia  

  echo ''
  echo "Successfully installed `julia -v`!"
  echo "Please reload this page (press Ctrl+R, ⌘+R, or the F5 key) then"
  echo "jump to the 'Checking the Installation' section."
fi

Installing Julia 1.6.0 on the current Colab Runtime...
2021-11-24 11:58:33 URL:https://storage.googleapis.com/julialang2/bin/linux/x64/1.6/julia-1.6.0-linux-x86_64.tar.gz [112838927/112838927] -> "/tmp/julia.tar.gz" [1]
Installing Julia package IJulia...
Installing IJulia kernel...
[ Info: Installing julia kernelspec in /root/.local/share/jupyter/kernels/julia-1.6

Please reload this page (press Ctrl+R, ⌘+R, or the F5 key) then
jump to the 'Checking the Installation' section.


## Checking the Installation
The `versioninfo()` function should print your Julia version and some other info about the system (if you ever ask for help or file an issue about Julia, you should always provide this information).

In [1]:
versioninfo()

Julia Version 1.6.0
Commit f9720dc2eb (2021-03-24 12:55 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU @ 2.20GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, broadwell)
Environment:
  JULIA_NUM_THREADS = 4


# Create a null vector of size 10

In [2]:
Z = zeros(Int8,10)
Z

10-element Vector{Int8}:
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0

# How to find the memory size of any array

In [3]:
Z = zeros(Int8,10,10)
Z

10×10 Matrix{Int8}:
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0

In [4]:
size_bytes(x) = Base.format_bytes(Base.summarysize(x))
size_bytes(Z)

"140 bytes"

# How to get the documentation of the numpy add function from the command line?

In [5]:
? +

search: +



```
+(x, y...)
```

Addition operator. `x+y+z+...` calls this function with all arguments, i.e. `+(x, y, z, ...)`.

# Examples

```jldoctest
julia> 1 + 20 + 4
25

julia> +(1, 20, 4)
25
```

---

```
dt::Date + t::Time -> DateTime
```

The addition of a `Date` with a `Time` produces a `DateTime`. The hour, minute, second, and millisecond parts of the `Time` are used along with the year, month, and day of the `Date` to create the new `DateTime`. Non-zero microseconds or nanoseconds in the `Time` type will result in an `InexactError` being thrown.


In [6]:
? zero

search: zero zeros iszero set_zero_subnormals get_zero_subnormals count_zeros



```
zero(x)
zero(::Type)
```

Get the additive identity element for the type of `x` (`x` can also specify the type itself).

# Examples

```jldoctest
julia> zero(1)
0

julia> zero(big"2.0")
0.0

julia> zero(rand(2,2))
2×2 Matrix{Float64}:
 0.0  0.0
 0.0  0.0
```


# Create a null vector of size 10 but the fifth value which is 1

In [7]:
Z = zeros(Int8,10)
Z[5] = 1
Z

10-element Vector{Int8}:
 0
 0
 0
 0
 1
 0
 0
 0
 0
 0

# Create a vector with values ranging from 10 to 49

In [8]:
Z = [10:50]

1-element Vector{UnitRange{Int64}}:
 10:50

In [9]:
# If you actually want it as an array for some reason 
Z = [10:50;]
Z

41-element Vector{Int64}:
 10
 11
 12
 13
 14
 15
 16
 17
 18
 19
 20
 21
 22
  ⋮
 39
 40
 41
 42
 43
 44
 45
 46
 47
 48
 49
 50

# Reverse a vector (first element becomes last)

In [14]:
Z = zeros(Int8,10)
Z[1] = 1
print(Z)
reverse!(Z)
Z

Int8[1, 0, 0, 0, 0, 0, 0, 0, 0, 0]

10-element Vector{Int8}:
 0
 0
 0
 0
 0
 0
 0
 0
 0
 1

# Create a 3x3 matrix with values ranging from 0 to 8


In [15]:
Z = [0:8;]
Z = reshape(Z,(3,3))

3×3 Matrix{Int64}:
 0  3  6
 1  4  7
 2  5  8

In [16]:
# This is likely a more efficient method
Z = reshape(Vector(0:8),(3,3))

3×3 Matrix{Int64}:
 0  3  6
 1  4  7
 2  5  8

# Find indices of non-zero elements from [1,2,0,0,4,0]

In [18]:
Z = [1,2,0,0,4,0]
print(findall(iszero,Z))
Z[findall(iszero,Z)]

[3, 4, 6]

3-element Vector{Int64}:
 0
 0
 0


# Create a 3x3 identity matrix

In [19]:
using LinearAlgebra

In [24]:
1.0I

# This is a really profound answer to the question involving a deep dive into Julia's philosophy and computing in general 
# https://stackoverflow.com/a/57270841/14274188 you should probably read this answer before using this particular code.

UniformScaling{Float64}
1.0*I

In [21]:
Z = Matrix{Int8}(I,3,3)

3×3 Matrix{Int8}:
 1  0  0
 0  1  0
 0  0  1

# Create a 3x3x3 array with random values

In [25]:
Z = rand(Int,(3,3,3))
Z

3×3×3 Array{Int64, 3}:
[:, :, 1] =
  2025818545162491277  -5004011121947301337     78510478484776030
 -6986836098498421102  -1927082601144293780  -6230548228136311590
 -1119470681674100077   1274727972511866118   1376793071672476938

[:, :, 2] =
 2485290277997527646   2698916363140861372   6481284117334849602
 6539159975492403814  -6932536654876002036  -5369097617728840068
 9029265133378003206   2013576055005798960   5792702691108009525

[:, :, 3] =
 -1905665437470542490   2043647704604339633  7894209513326539539
 -9081042175198700342  -8821711965611780600  -762520677764284151
  -602323526464656665  -5535305010381233077  1903472580713990027

# Create a 10x10 array with random values and find the minimum and maximum values

In [26]:
Z = rand(Int,(10,10))

10×10 Matrix{Int64}:
 -4990422968709066729   8494069964343846394  …    115981381765040620
  6839189018105029596   5500788885065196375      6542314436410627193
  1754370153137028899  -3394508504459115049     -7133721600978812261
  5615605781107970765  -2109525245717529388     -5261698418702985856
  6431924159725991864   7332250437803522119     -4898134576404984865
 -6829416285815620346    204178758579116297  …   7593025634835331158
 -4757683895678537377   1267903546629301037     -2116264688230408196
 -7803412813320467779  -4815402684195215086     -2301460803809973263
  2324980312156152153  -4603970734305999429      1894553696248987463
  -757305464848934221   5474673657578226709      8705440285181533479

In [28]:
minimum(Z)

-9060217979172525793

In [29]:
maximum(Z)

9145675291967614126