# Getting Started with Julia in Colab/Jupyter
You can either run this notebook in Google Colab, or using Jupyter on your own machine.

## Running on Google Colab
1. Work on a copy of this notebook: _File_ > _Save a copy in Drive_ (you will need a Google account). Alternatively, you can download the notebook using _File_ > _Download .ipynb_, then upload it to [Colab](https://colab.research.google.com/).
2. Execute the following cell (click on it and press Ctrl+Enter) to install Julia, IJulia (the Jupyter kernel for Julia) and other packages. You can update `JULIA_VERSION` and the other parameters, if you know what you're doing. Installation takes 2-3 minutes.
3. Reload this page (press Ctrl+R, or ⌘+R, or the F5 key) and continue to the _Checking the Installation_ section.

* _Note_: If your Colab Runtime gets reset (e.g., due to inactivity), repeat steps 2 and 3.

In [ ]:
%%shell
set -e

#---------------------------------------------------#
JULIA_VERSION="1.6.0" # any version ≥ 0.7.0
JULIA_PACKAGES="IJulia"
JULIA_PACKAGES_IF_GPU="CUDA"
JULIA_NUM_THREADS=4
#---------------------------------------------------#

if [ -n "$COLAB_GPU" ] && [ -z `which julia` ]; then
  # Install Julia
  JULIA_VER=`cut -d '.' -f -2 <<< "$JULIA_VERSION"`
  echo "Installing Julia $JULIA_VERSION on the current Colab Runtime..."
  BASE_URL="https://julialang-s3.julialang.org/bin/linux/x64"
  URL="$BASE_URL/$JULIA_VER/julia-$JULIA_VERSION-linux-x86_64.tar.gz"
  wget -nv $URL -O /tmp/julia.tar.gz # -nv means "not verbose"
  tar -x -f /tmp/julia.tar.gz -C /usr/local --strip-components 1
  rm /tmp/julia.tar.gz

  # Install Packages
  if [ "$COLAB_GPU" = "1" ]; then
      JULIA_PACKAGES="$JULIA_PACKAGES $JULIA_PACKAGES_IF_GPU"
  fi
  for PKG in `echo $JULIA_PACKAGES`; do
    echo "Installing Julia package $PKG..."
    julia -e 'using Pkg; pkg"add '$PKG'; precompile;"' &> /dev/null
  done

  # Install kernel and rename it to "julia"
  echo "Installing IJulia kernel..."
  julia -e 'using IJulia; IJulia.installkernel("julia", env=Dict(
      "JULIA_NUM_THREADS"=>"'"$JULIA_NUM_THREADS"'"))'
  KERNEL_DIR=`julia -e "using IJulia; print(IJulia.kerneldir())"`
  KERNEL_NAME=`ls -d "$KERNEL_DIR"/julia*`
  mv -f $KERNEL_NAME "$KERNEL_DIR"/julia  

  echo ''
  echo "Successfully installed `julia -v`!"
  echo "Please reload this page (press Ctrl+R, ⌘+R, or the F5 key) then"
  echo "jump to the 'Checking the Installation' section."
fi

Installing Julia 1.6.0 on the current Colab Runtime...
2021-11-28 06:40:27 URL:https://storage.googleapis.com/julialang2/bin/linux/x64/1.6/julia-1.6.0-linux-x86_64.tar.gz [112838927/112838927] -> "/tmp/julia.tar.gz" [1]
Installing Julia package IJulia...


## Checking the Installation
The `versioninfo()` function should print your Julia version and some other info about the system (if you ever ask for help or file an issue about Julia, you should always provide this information).

In [1]:
versioninfo()

Julia Version 1.6.0
Commit f9720dc2eb (2021-03-24 12:55 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU @ 2.20GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, broadwell)
Environment:
  JULIA_NUM_THREADS = 4


In [2]:
using Statistics
using LinearAlgebra

# Create a null vector of size 10

In [3]:
Z = zeros(Int8,10)
Z

10-element Vector{Int8}:
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0

# How to find the memory size of any array

In [4]:
Z = zeros(Int8,10,10)
Z

10×10 Matrix{Int8}:
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0

In [5]:
size_bytes(x) = Base.format_bytes(Base.summarysize(x))
size_bytes(Z)

"140 bytes"

# How to get the documentation of the numpy add function from the command line?

In [6]:
? +

search: +



```
+(x, y...)
```

Addition operator. `x+y+z+...` calls this function with all arguments, i.e. `+(x, y, z, ...)`.

# Examples

```jldoctest
julia> 1 + 20 + 4
25

julia> +(1, 20, 4)
25
```

---

```
dt::Date + t::Time -> DateTime
```

The addition of a `Date` with a `Time` produces a `DateTime`. The hour, minute, second, and millisecond parts of the `Time` are used along with the year, month, and day of the `Date` to create the new `DateTime`. Non-zero microseconds or nanoseconds in the `Time` type will result in an `InexactError` being thrown.


In [7]:
? zero

search: zero zeros ZeroPivotException iszero set_zero_subnormals



```
zero(x)
zero(::Type)
```

Get the additive identity element for the type of `x` (`x` can also specify the type itself).

# Examples

```jldoctest
julia> zero(1)
0

julia> zero(big"2.0")
0.0

julia> zero(rand(2,2))
2×2 Matrix{Float64}:
 0.0  0.0
 0.0  0.0
```


# Create a null vector of size 10 but the fifth value which is 1

In [8]:
Z = zeros(Int8,10)
Z[5] = 1
Z

10-element Vector{Int8}:
 0
 0
 0
 0
 1
 0
 0
 0
 0
 0

# Create a vector with values ranging from 10 to 49

In [9]:
Z = [10:50]

1-element Vector{UnitRange{Int64}}:
 10:50

In [10]:
# If you actually want it as an array for some reason 
Z = [10:50;]
Z

41-element Vector{Int64}:
 10
 11
 12
 13
 14
 15
 16
 17
 18
 19
 20
 21
 22
  ⋮
 39
 40
 41
 42
 43
 44
 45
 46
 47
 48
 49
 50

# Reverse a vector (first element becomes last)

In [11]:
Z = zeros(Int8,10)
Z[1] = 1
print(Z)
reverse!(Z)
Z

Int8[1, 0, 0, 0, 0, 0, 0, 0, 0, 0]

10-element Vector{Int8}:
 0
 0
 0
 0
 0
 0
 0
 0
 0
 1

# Create a 3x3 matrix with values ranging from 0 to 8


In [12]:
Z = [0:8;]
Z = reshape(Z,(3,3))

3×3 Matrix{Int64}:
 0  3  6
 1  4  7
 2  5  8

In [13]:
# This is likely a more efficient method
Z = reshape(Vector(0:8),(3,3))

3×3 Matrix{Int64}:
 0  3  6
 1  4  7
 2  5  8

# Find indices of non-zero elements from [1,2,0,0,4,0]

In [14]:
Z = [1,2,0,0,4,0]
print(findall(iszero,Z))
Z[findall(iszero,Z)]

[3, 4, 6]

3-element Vector{Int64}:
 0
 0
 0


# Create a 3x3 identity matrix

In [15]:
1.0I

# This is a really profound answer to the question involving a deep dive into Julia's philosophy and computing in general 
# https://stackoverflow.com/a/57270841/14274188 you should probably read this answer before using this particular code.

UniformScaling{Float64}
1.0*I

In [16]:
Z = Matrix{Int8}(I,3,3)

3×3 Matrix{Int8}:
 1  0  0
 0  1  0
 0  0  1

# Create a 3x3x3 array with random values

In [17]:
Z = rand(Int,(3,3,3))
Z

3×3×3 Array{Int64, 3}:
[:, :, 1] =
  3806894042569051247   4101518327781929558  -1150304688222447421
 -3277525164774597182  -6463279504882795793  -7980997582630556490
  7826772888706282894    306054472605053367  -5371480206392349910

[:, :, 2] =
  1289977229484553236   3938500722541033500   4876974976525267036
 -1576304082926897534   4385421370996008294  -2949257984507509891
  6001675682280131504  -1274535198128224250  -1288257064502693070

[:, :, 3] =
 -1951704615192023486  7716636441803374061   2706844704943953045
  8929345148110218645  5856962545594183628  -8286584318678297752
 -9221840343158891798  5923754033697200389  -7403669699682711298

# Create a 10x10 array with random values and find the minimum and maximum values

In [18]:
Z = rand(Int,(10,10))

10×10 Matrix{Int64}:
  8186878226763047473  -9061253665245106535  …   4584911385175654579
   789579274104018425  -2711451338804233736      5855255920722501793
 -3130357512898994843   5155091658295721044       411872609743282525
 -8163891628722545989   7173529375598747128       983983685559597096
  5796772511379017056   6897643672438189765     -7787755882843258119
  5831733614204122863  -3740915373095645012  …   3457290088962158358
  8682247887719888501   2603803061889133125     -2422754672030248713
  -388178716004715686  -7949075524816915036      -572782547475185482
  1587668665691496384   5463984260434844336      3918008123423433399
  8688559849993981569   1927903474735859516     -2358643879546315615

In [19]:
minimum(Z)

-9061253665245106535

In [20]:
maximum(Z)

8857838714455764006

# Create a random vector of size 30 and find the mean value

In [21]:
Z = Vector(rand(Int,10))

# Kinda basic method
sum(Z)/length(Z)

-8.140793158410106e17

In [22]:
# This is not a part of the standard library and is instead imported from Statistics, yes not one of the best decisions Julia ever made
mean(Z)

-2.658753723211966e18

# Create a 2d array with 1 on the border and 0 inside

In [23]:
Z = ones(10, 10)
Z[2:end-1, 2:end-1] .= 0
Z
# Okay there are a few bits here that we have to address:
# Right of the bat Julia uses 1-based indexing as you probably already know
# The end keyword represents the end of a dimension in Julia, It provides a more explicit way to specify indexes.
# Finally the . operator is used for broadcasting. Julia does not automatically write 0 everywhere if you use just the assignment operator. This can often trip people and instead the . operator provides an explicit broadcasting method

10×10 Matrix{Float64}:
 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0
 1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0
 1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0
 1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0
 1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0
 1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0
 1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0
 1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0
 1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0
 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0

# How to add a border (filled with 0's) around an existing array?

In [24]:
len_mat = 9
Z = ones(Int8, len_mat, len_mat)
borderZ = zeros(Int8, len_mat + 2, len_mat + 2)
borderZ[2:end-1, 2:end-1] = Z
borderZ
# Ok so this is very much an extremely hacky way to do this but I could find a good way to go about this.
# If you are using this in a context of images processing then Image Filtering has a way described here https://discourse.julialang.org/t/is-there-any-padding-function-available-to-pad-a-matrix-or-array/8521/3
# PaddedViews.jl might be an option too if you are using this a lot

11×11 Matrix{Int8}:
 0  0  0  0  0  0  0  0  0  0  0
 0  1  1  1  1  1  1  1  1  1  0
 0  1  1  1  1  1  1  1  1  1  0
 0  1  1  1  1  1  1  1  1  1  0
 0  1  1  1  1  1  1  1  1  1  0
 0  1  1  1  1  1  1  1  1  1  0
 0  1  1  1  1  1  1  1  1  1  0
 0  1  1  1  1  1  1  1  1  1  0
 0  1  1  1  1  1  1  1  1  1  0
 0  1  1  1  1  1  1  1  1  1  0
 0  0  0  0  0  0  0  0  0  0  0

In [25]:
Z = ones(Int8,9,9)

9×9 Matrix{Int8}:
 1  1  1  1  1  1  1  1  1
 1  1  1  1  1  1  1  1  1
 1  1  1  1  1  1  1  1  1
 1  1  1  1  1  1  1  1  1
 1  1  1  1  1  1  1  1  1
 1  1  1  1  1  1  1  1  1
 1  1  1  1  1  1  1  1  1
 1  1  1  1  1  1  1  1  1
 1  1  1  1  1  1  1  1  1

# Create a 5x5 matrix with values 1,2,3,4 just below the diagonal 

In [29]:
diagonal = [1, 2, 3, 4]
ld = Bidiagonal(zeros(5), diagonal, :L)
# : in this context is an identifier essentially used to identify an entity. Here if you use :U instead, that uses a different implementation which would place the diagonal vector on top of zeros instead

5×5 Bidiagonal{Float64, Vector{Float64}}:
 0.0   ⋅    ⋅    ⋅    ⋅ 
 1.0  0.0   ⋅    ⋅    ⋅ 
  ⋅   2.0  0.0   ⋅    ⋅ 
  ⋅    ⋅   3.0  0.0   ⋅ 
  ⋅    ⋅    ⋅   4.0  0.0

# Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [36]:
arr = rand(Int8, (6, 7, 8))
c_x = CartesianIndices(arr)
arr[c_x[100]]

66

# Create a checkerboard 8x8 matrix using the tile function

In [38]:
base_mat = [[1, 0] [0, 1]]
repeat(base_mat,4,4)

8×8 Matrix{Int64}:
 1  0  1  0  1  0  1  0
 0  1  0  1  0  1  0  1
 1  0  1  0  1  0  1  0
 0  1  0  1  0  1  0  1
 1  0  1  0  1  0  1  0
 0  1  0  1  0  1  0  1
 1  0  1  0  1  0  1  0
 0  1  0  1  0  1  0  1