# Getting Started with Julia in Colab/Jupyter
You can either run this notebook in Google Colab, or using Jupyter on your own machine.

## Running on Google Colab
1. Work on a copy of this notebook: _File_ > _Save a copy in Drive_ (you will need a Google account). Alternatively, you can download the notebook using _File_ > _Download .ipynb_, then upload it to [Colab](https://colab.research.google.com/).
2. Execute the following cell (click on it and press Ctrl+Enter) to install Julia, IJulia (the Jupyter kernel for Julia) and other packages. You can update `JULIA_VERSION` and the other parameters, if you know what you're doing. Installation takes 2-3 minutes.
3. Reload this page (press Ctrl+R, or ⌘+R, or the F5 key) and continue to the _Checking the Installation_ section.

* _Note_: If your Colab Runtime gets reset (e.g., due to inactivity), repeat steps 2 and 3.

In [ ]:
%%shell
set -e

#---------------------------------------------------#
JULIA_VERSION="1.6.0" # any version ≥ 0.7.0
JULIA_PACKAGES="IJulia"
JULIA_PACKAGES_IF_GPU="CUDA"
JULIA_NUM_THREADS=4
#---------------------------------------------------#

if [ -n "$COLAB_GPU" ] && [ -z `which julia` ]; then
  # Install Julia
  JULIA_VER=`cut -d '.' -f -2 <<< "$JULIA_VERSION"`
  echo "Installing Julia $JULIA_VERSION on the current Colab Runtime..."
  BASE_URL="https://julialang-s3.julialang.org/bin/linux/x64"
  URL="$BASE_URL/$JULIA_VER/julia-$JULIA_VERSION-linux-x86_64.tar.gz"
  wget -nv $URL -O /tmp/julia.tar.gz # -nv means "not verbose"
  tar -x -f /tmp/julia.tar.gz -C /usr/local --strip-components 1
  rm /tmp/julia.tar.gz

  # Install Packages
  if [ "$COLAB_GPU" = "1" ]; then
      JULIA_PACKAGES="$JULIA_PACKAGES $JULIA_PACKAGES_IF_GPU"
  fi
  for PKG in `echo $JULIA_PACKAGES`; do
    echo "Installing Julia package $PKG..."
    julia -e 'using Pkg; pkg"add '$PKG'; precompile;"' &> /dev/null
  done

  # Install kernel and rename it to "julia"
  echo "Installing IJulia kernel..."
  julia -e 'using IJulia; IJulia.installkernel("julia", env=Dict(
      "JULIA_NUM_THREADS"=>"'"$JULIA_NUM_THREADS"'"))'
  KERNEL_DIR=`julia -e "using IJulia; print(IJulia.kerneldir())"`
  KERNEL_NAME=`ls -d "$KERNEL_DIR"/julia*`
  mv -f $KERNEL_NAME "$KERNEL_DIR"/julia  

  echo ''
  echo "Successfully installed `julia -v`!"
  echo "Please reload this page (press Ctrl+R, ⌘+R, or the F5 key) then"
  echo "jump to the 'Checking the Installation' section."
fi

Installing Julia 1.6.0 on the current Colab Runtime...
2021-12-03 12:13:46 URL:https://storage.googleapis.com/julialang2/bin/linux/x64/1.6/julia-1.6.0-linux-x86_64.tar.gz [112838927/112838927] -> "/tmp/julia.tar.gz" [1]
Installing Julia package IJulia...


## Checking the Installation
The `versioninfo()` function should print your Julia version and some other info about the system (if you ever ask for help or file an issue about Julia, you should always provide this information).

In [1]:
versioninfo()

Julia Version 1.6.0
Commit f9720dc2eb (2021-03-24 12:55 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU @ 2.20GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, broadwell)
Environment:
  JULIA_NUM_THREADS = 4


In [2]:
using LinearAlgebra
using Statistics
using Dates

# Create a null vector of size 10

In [ ]:
Z = zeros(Int8,10)
Z

10-element Vector{Int8}:
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0

# How to find the memory size of any array

In [ ]:
Z = zeros(Int8,10,10)
Z

10×10 Matrix{Int8}:
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0

In [ ]:
size_bytes(x) = Base.format_bytes(Base.summarysize(x))
size_bytes(Z)

"140 bytes"

# How to get the documentation of the numpy add function from the command line?

In [ ]:
? +

search: +



```
+(x, y...)
```

Addition operator. `x+y+z+...` calls this function with all arguments, i.e. `+(x, y, z, ...)`.

# Examples

```jldoctest
julia> 1 + 20 + 4
25

julia> +(1, 20, 4)
25
```

---

```
dt::Date + t::Time -> DateTime
```

The addition of a `Date` with a `Time` produces a `DateTime`. The hour, minute, second, and millisecond parts of the `Time` are used along with the year, month, and day of the `Date` to create the new `DateTime`. Non-zero microseconds or nanoseconds in the `Time` type will result in an `InexactError` being thrown.


In [ ]:
? zero

search: zero zeros ZeroPivotException iszero set_zero_subnormals



```
zero(x)
zero(::Type)
```

Get the additive identity element for the type of `x` (`x` can also specify the type itself).

# Examples

```jldoctest
julia> zero(1)
0

julia> zero(big"2.0")
0.0

julia> zero(rand(2,2))
2×2 Matrix{Float64}:
 0.0  0.0
 0.0  0.0
```


# Create a null vector of size 10 but the fifth value which is 1

In [ ]:
Z = zeros(Int8,10)
Z[5] = 1
Z

10-element Vector{Int8}:
 0
 0
 0
 0
 1
 0
 0
 0
 0
 0

# Create a vector with values ranging from 10 to 49

In [ ]:
Z = [10:50]

1-element Vector{UnitRange{Int64}}:
 10:50

In [ ]:
# If you actually want it as an array for some reason 
Z = [10:50;]
Z

41-element Vector{Int64}:
 10
 11
 12
 13
 14
 15
 16
 17
 18
 19
 20
 21
 22
  ⋮
 39
 40
 41
 42
 43
 44
 45
 46
 47
 48
 49
 50

# Reverse a vector (first element becomes last)

In [ ]:
Z = zeros(Int8,10)
Z[1] = 1
print(Z)
reverse!(Z)
Z

Int8[1, 0, 0, 0, 0, 0, 0, 0, 0, 0]

10-element Vector{Int8}:
 0
 0
 0
 0
 0
 0
 0
 0
 0
 1

# Create a 3x3 matrix with values ranging from 0 to 8


In [ ]:
Z = [0:8;]
Z = reshape(Z,(3,3))

3×3 Matrix{Int64}:
 0  3  6
 1  4  7
 2  5  8

In [ ]:
# This is likely a more efficient method
Z = reshape(Vector(0:8),(3,3))

3×3 Matrix{Int64}:
 0  3  6
 1  4  7
 2  5  8

# Find indices of non-zero elements from [1,2,0,0,4,0]

In [ ]:
Z = [1,2,0,0,4,0]
print(findall(iszero,Z))
Z[findall(iszero,Z)]

[3, 4, 6]

3-element Vector{Int64}:
 0
 0
 0


# Create a 3x3 identity matrix

In [ ]:
1.0I

# This is a really profound answer to the question involving a deep dive into Julia's philosophy and computing in general 
# https://stackoverflow.com/a/57270841/14274188 you should probably read this answer before using this particular code.

UniformScaling{Float64}
1.0*I

In [ ]:
Z = Matrix{Int8}(I,3,3)

3×3 Matrix{Int8}:
 1  0  0
 0  1  0
 0  0  1

# Create a 3x3x3 array with random values

In [ ]:
Z = rand(Int,(3,3,3))
Z

3×3×3 Array{Int64, 3}:
[:, :, 1] =
  4462908829605962438    134302792482007180  -7956179272859891739
  2981306165387387579   3581256372772647984   8606531549616035471
 -6097961447878653192  -8858731737544484284    830913414455537103

[:, :, 2] =
 -4472004227723680912  -1630895733236584839   6553962686451055036
 -5914603710251515434   5080995073221745262  -4291374127656017696
  -765633332705086920   8530467140906831049  -1944869856493258312

[:, :, 3] =
  2911047806318721060  -3916778472331591230  4668299566307002197
  4347163637967513912   1155511578770476134  7726494007386633838
 -2161395321096942034   3276861275716063211  1700942163756210471

# Create a 10x10 array with random values and find the minimum and maximum values

In [ ]:
Z = rand(Int,(10,10))

10×10 Matrix{Int64}:
   105678209628116255    458421571942946441  …  -8046476735864562858
 -6700661862063558822   1035403805771218935      7382587930512975098
 -9125283499761694147   2318493393881934630      5014774468533236524
  8437137691564160817  -7972308997102519223     -1399364942828559626
  3430478179138309682    657734625547908440      9036488159156928476
 -6888822698525268022   3149960591336803417  …   3895098868142242616
 -5857357756736695334   5605354194626360352      1852440565676658040
 -7157657714130360465   6216124641877313875      7017030997042407279
 -5345135659082176900  -6738613632553321418      3388480646439948835
 -4173666456499112126   -891379073152200568     -6292615590098464107

In [ ]:
minimum(Z)

-9132762714347779880

In [ ]:
maximum(Z)

9076002593816569733

# Create a random vector of size 30 and find the mean value

In [ ]:
Z = Vector(rand(Int,10))

# Kinda basic method
sum(Z)/length(Z)

3.5199879376014406e17

In [ ]:
# This is not a part of the standard library and is instead imported from Statistics, yes not one of the best decisions Julia ever made
mean(Z)

-1.492675613610811e18

# Create a 2d array with 1 on the border and 0 inside

In [ ]:
Z = ones(10, 10)
Z[2:end-1, 2:end-1] .= 0
Z
# Okay there are a few bits here that we have to address:
# Right of the bat Julia uses 1-based indexing as you probably already know
# The end keyword represents the end of a dimension in Julia, It provides a more explicit way to specify indexes.
# Finally the . operator is used for broadcasting. Julia does not automatically write 0 everywhere if you use just the assignment operator. This can often trip people and instead the . operator provides an explicit broadcasting method

10×10 Matrix{Float64}:
 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0
 1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0
 1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0
 1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0
 1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0
 1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0
 1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0
 1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0
 1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0
 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0

# How to add a border (filled with 0's) around an existing array?

In [ ]:
len_mat = 9
Z = ones(Int8, len_mat, len_mat)
borderZ = zeros(Int8, len_mat + 2, len_mat + 2)
borderZ[2:end-1, 2:end-1] = Z
borderZ
# Ok so this is very much an extremely hacky way to do this but I could find a good way to go about this.
# If you are using this in a context of images processing then Image Filtering has a way described here https://discourse.julialang.org/t/is-there-any-padding-function-available-to-pad-a-matrix-or-array/8521/3
# PaddedViews.jl might be an option too if you are using this a lot

11×11 Matrix{Int8}:
 0  0  0  0  0  0  0  0  0  0  0
 0  1  1  1  1  1  1  1  1  1  0
 0  1  1  1  1  1  1  1  1  1  0
 0  1  1  1  1  1  1  1  1  1  0
 0  1  1  1  1  1  1  1  1  1  0
 0  1  1  1  1  1  1  1  1  1  0
 0  1  1  1  1  1  1  1  1  1  0
 0  1  1  1  1  1  1  1  1  1  0
 0  1  1  1  1  1  1  1  1  1  0
 0  1  1  1  1  1  1  1  1  1  0
 0  0  0  0  0  0  0  0  0  0  0

In [ ]:
Z = ones(Int8,9,9)

9×9 Matrix{Int8}:
 1  1  1  1  1  1  1  1  1
 1  1  1  1  1  1  1  1  1
 1  1  1  1  1  1  1  1  1
 1  1  1  1  1  1  1  1  1
 1  1  1  1  1  1  1  1  1
 1  1  1  1  1  1  1  1  1
 1  1  1  1  1  1  1  1  1
 1  1  1  1  1  1  1  1  1
 1  1  1  1  1  1  1  1  1

# Create a 5x5 matrix with values 1,2,3,4 just below the diagonal 

In [ ]:
diagonal = [1, 2, 3, 4]
ld = Bidiagonal(zeros(5), diagonal, :L)
# : in this context is an identifier essentially used to identify an entity. Here if you use :U instead, that uses a different implementation which would place the diagonal vector on top of zeros instead

5×5 Bidiagonal{Float64, Vector{Float64}}:
 0.0   ⋅    ⋅    ⋅    ⋅ 
 1.0  0.0   ⋅    ⋅    ⋅ 
  ⋅   2.0  0.0   ⋅    ⋅ 
  ⋅    ⋅   3.0  0.0   ⋅ 
  ⋅    ⋅    ⋅   4.0  0.0

# Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [ ]:
arr = rand(Int8, (6, 7, 8))
c_x = CartesianIndices(arr)
arr[c_x[100]]

68

# Create a checkerboard 8x8 matrix using the tile function

In [ ]:
base_mat = [[1, 0] [0, 1]]
repeat(base_mat,4,4)

8×8 Matrix{Int64}:
 1  0  1  0  1  0  1  0
 0  1  0  1  0  1  0  1
 1  0  1  0  1  0  1  0
 0  1  0  1  0  1  0  1
 1  0  1  0  1  0  1  0
 0  1  0  1  0  1  0  1
 1  0  1  0  1  0  1  0
 0  1  0  1  0  1  0  1

# Normalize a 5x5 random matrix

In [ ]:
Z = 2rand(5,5)

5×5 Matrix{Float64}:
 0.300465  1.1871    1.24643   1.69243   0.421033
 0.309838  0.094943  1.30473   1.06546   1.58777
 1.54115   1.56349   1.6445    1.44416   0.0296642
 0.123874  1.75054   0.716102  0.366441  0.232255
 1.83308   1.23933   1.5344    0.379556  1.90608

In [ ]:
normalize!(Z)

5×5 Matrix{Float64}:
 0.0500934  0.197913   0.207804  0.282161   0.0701943
 0.051656   0.0158289  0.217524  0.177633   0.264713
 0.25694    0.260664   0.27417   0.24077    0.0049456
 0.0206522  0.29185    0.119388  0.0610928  0.0387214
 0.305609   0.20662    0.255815  0.0632794  0.317781

# Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

In [ ]:
Z₁ = ones(5,3)
Z₂ = ones(3,2)
Z₁*Z₂
# Yeah bit of a show off but that's just objectively cool

5×2 Matrix{Float64}:
 3.0  3.0
 3.0  3.0
 3.0  3.0
 3.0  3.0
 3.0  3.0

# Given a 1D array, negate all elements which are between 3 and 8, in place.

In [ ]:
Z = [1:11;]
replace!(x -> (3 .<= x .<= 8) ? -x : x,Z)

11-element Vector{Int64}:
  1
  2
 -3
 -4
 -5
 -6
 -7
 -8
  9
 10
 11

# How to round away from zero a float array ?

In [ ]:
Z = [-0.5:0.1:0.5;]
replace!(x -> x > 0 ? ceil(x) : floor(x), Z)

11-element Vector{Float64}:
 -1.0
 -1.0
 -1.0
 -1.0
 -1.0
  0.0
  1.0
  1.0
  1.0
  1.0
  1.0

# How to find common values between two arrays?

In [ ]:
Z₁ = rand(1:10, 10)
Z₂ = rand(1:10, 10)
intersect(Z₁, Z₂)

4-element Vector{Int64}:
 2
 6
 8
 5

# How to get the dates of yesterday, today and tomorrow?

In [ ]:
today = Dates.today()
print("$(today)\n")
yesterday = today - Dates.Day(1)
print("$(yesterday)\n")
tomorrow = today + Dates.Day(1)
print("$(tomorrow)\n")

2021-11-30
2021-11-29
2021-12-01


# Consider a generator function that generates 10 integers and use it to build an array

In [5]:
int_gen = (x for x = 1:10)
collect(int_gen)

10-element Vector{Int64}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10